[package]
name                   = "oxc_span"
version                = "0.12.5"
publish                = true
authors.workspace      = true
description.workspace  = true
edition.workspace      = true
homepage.workspace     = true
keywords.workspace     = true
license.workspace      = true
repository.workspace   = true
rust-version.workspace = true
categories.workspace   = true

[lints]
workspace = true

[lib]
doctest = false

[dependencies]
oxc_macros = { workspace = true }

miette      = { workspace = true }
compact_str = { workspace = true }

tsify        = { workspace = true, optional = true }
wasm-bindgen = { workspace = true, optional = true }
serde        = { workspace = true, features = ["derive"], optional = true }

layout_inspect = { workspace = true, features = ["unique_names"], optional = true }

[features]
default   = []
raw       = ["serialize", "dep:layout_inspect"]
serialize = ["dep:serde", "dep:tsify", "dep:wasm-bindgen", "compact_str/serde"]

[package.metadata.cargo-shear]
ignored = ["layout_inspect"]
